### ISSUE TITLE
Programmatically focus first child

### ISSUE THREAD

**Issue by cfhull** [stevejay/react-roving-tabindex#17]
I'm using `react-roving-tab-index` for a filterable list. I would like the user to be able to enter a value into a text box and be able to press the down arrow to focus the first item, and then continue use the arrow keys to move through the list as normal.

I tried storing a ref to the list items, and manually called `ref.current[0].focus()` which generally works, except in this specific case.

[demo](https://codesandbox.io/s/lucid-satoshi-pun1c)

1. Click or tab into the input box.
2. Type some letters.
3. Press the down arrow to focus the first item.
4. Press the down arrow to focus the second item.
5. Press the up arrow to select the first item. (If you skip this step, or continue pressing the down arrow only, it ends up still working)
6. Click away from the items to lose focus.
7. Press tab to focus the input.
8. Press down to focus the first item.
9. Try to press down, but it no longer works, although it starts working again if you press up

These specific steps cause the issue consistently, but the issue seems rather inconsistent if you continue to mess around with the arrow keys and shift-tab to bounce between the items and the input. 

I'm hoping I'm overthinking things and there's an easier way to handle this use case.

Thanks!

**Comment by stevejay** [comment]
Hi! I'm not quite sure how this widget should work. If the intent is for the list of items to be displayed permanently below the input field then I would probably expect to use tab to move from the input field to the list of items. (I presume you then want that list of items to use a roving tab index.) I normally think of down arrow usage -- to move from an input to a list of items -- in terms of a combobox, in which case the combobox implementation handles arrow handling and the list of items only displays on interacting with the input field.

That said, I see the issue with the sandbox you've linked to: when focus is in the input field and the user presses the down key, the list item to focus must be the item that is the focusable one in the roving tabindex group, and that item isn't necessarily the first one. So the line `ref.current[0].focus()` is causing the issue here. I've forked the sandbox to show an imperative-style fix: https://codesandbox.io/s/vigorous-lederberg-m6ebx . The relevant line is now `listRef.current.querySelector('[tabindex="0"]').focus();`. You may be able to find a more React-like way to find or keep track of the list item that is the currently active one in the roving tabindex group.

**Comment by cfhull** [comment]
That does fix the issue with it getting stuck, but in my use case, we need the down arrow to always select the first item. 

This makes a little more sense when the list becomes searchable, as I've added here: https://codesandbox.io/s/boring-babbage-39f7k. This logic doesn't seem to work if you have banana selected, and then change the filter to `Ap`. As you're typing and Banana gets removed, it auto-focuses the first item.

I also tried this with setting the non-matching items to disabled in the `useRovingTabIndex` hook instead of removing them from the array, but it still seems to auto-focus the first item once the focus item becomes disabled.

I think what I need is to be able to reset the focused item to the default when I lose focus on the list. I don't think I can just hack tab-indexes in the DOM because it would become out of sync with the internal state of the provider context.

What do you think? I understand if this is becoming too specific of a use case for this tool, but I appreciate your input.

**Comment by stevejay** [comment]
So this library is definitely not intended for a use case of programmatically taking control over which item is focused. Certainly resetting the focused item to the default when focus is lost on the list defeats the purpose of the roving tabindex concept. It may be that you wanted the ability to use arrow keys to move up and down a list of items, and so that part of this library appears useful, but I don't think it's actually a good fit. It sounds like a library like [downshift](https://github.com/downshift-js/downshift) (which I've used and is awesome) would be more appropriate for this widget.

**Comment by cfhull** [comment]
Thanks, I'll check it out. For what it's worth, I did figure out how to prevent it from jumping to the first item while I was filtering the list. In hindsight it's obvious, but I had to replace the `useFocusEffect` hook with a custom effect to prevent the focus if the input box was selected. It was quite ugly though.
