### ISSUE TITLE
Support navigating across table rows

### ISSUE THREAD

**Issue by droidenator** [stevejay/react-roving-tabindex#26]
I'm wanting to use this component to implement a roving tab index on a data grid I'm building using tables. The keyboard navigation works great for going between columns but there's no way to move between rows using the up and down arrows.

Is this something you'd want to support in this component? I'd be glad to take a shot at implementing the feature and submitting a PR.

**Comment by stevejay** [comment]
Hi! I think that this library is better kept as a simple roving tabindex. This library is really for a collection of simple controls, for example in a toolbar. I personally feel that a data grid might benefit from a11y support that can evolve with the business requirements, rather than being constrained to using a generalized solution. That said, there have been a couple of forks that have added grid support and you might find them useful: 
- https://github.com/gabycperezdias/react-roving-tabindex
- https://github.com/goelrohan6/react-roving-tabindex

**Comment by droidenator** [comment]
Sounds good. I'll check out those forks. Thanks!

**Comment by stevejay** [comment]
@droidenator Changed my mind 🙄 There's now a `feature/v2` branch with grid support, published to npm as `2.0.0-beta.4`. The readme is [here](https://github.com/stevejay/react-roving-tabindex/blob/feature/v2/README.md). If you happen to get a moment then I'd appreciate any feedback about the `rowIndex` parameter API or thoughts on any of the other changes in v2.
