### ISSUE TITLE
Lazy components

### ISSUE THREAD

**Issue by diegohaz** [stevejay/react-roving-tabindex#3]
Hi @stevejay. 

I'm trying to create a solution for roving tabindex in React. I've come up with a solution very similar to yours, which I found during my research.

However, I've found out that it doesn't work when components are added late in the DOM, like this:

```jsx
<Rover />
{condition && <Rover />}
<Rover />
```

It results in the second `<Rover />` being added in the last position of the tab order, which will break the user expectation.

One way to avoid this, of course, is to not render components lazily. But I don't think it's a good idea to impose this limitation. With `React.lazy` and concurrent mode, that will be even more common.

Do you have any idea how to solve this?

**Comment by stevejay** [comment]
Hi! I agree that it’s not a good limitation when you want a dynamic roving tabindex. Do you mean that it’s the solution you’re working on that has this limitation or is it my implementation with that limitation?

**Comment by diegohaz** [comment]
Your solution works. I was trying to find why. I guess that's because of these lines, right?
https://github.com/stevejay/react-roving-tabindex/blob/0f3a8521e16b47e600df1c54f263a5e5b25af1d0/src/Provider.tsx#L70-L73

**Comment by stevejay** [comment]
Yep, that's correct. The issue is that I need to be able to know the position of one element relative to another, and React itself does not have an API for that. So I have to use the browser's [compareDocumentPosition](https://developer.mozilla.org/en-US/docs/Web/API/Node/compareDocumentPosition) API, which is actually very well supported.
