### ISSUE TITLE
Use options as separate props in the provider

### ISSUE THREAD

**Issue by kripod** [stevejay/react-roving-tabindex#39]
According to [this article](https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/#how-new-props-references-affect-render-optimizations),

> React re-renders all nested components even if their props haven't changed.

The `options` prop takes an object and unlike with primitives (strings, numbers, etc.), it always marks the props as changed when redefined inside the component on each render, initiating a rerender for the children.

I would like to suggest extracting `options` into separate props for `direction`, `focusOnClick` and `loopAround`, as follows, to avoid unnecessary rerenders of child nodes:

```jsx
const SomeComponent = () => (
  <RovingTabIndexProvider direction="vertical" focusOnClick>
    {/* whatever */}
  </RovingTabIndexProvider>
);
```

**Comment by stevejay** [comment]
Good catch 👍  In fact it's for that reason why I used `useMemo` within the Provider to cache the context value, but it didn't occur to me that it's a problem here. It's frustrating that I've already pushed v3, so any change to the options is now another breaking change.

**Comment by stevejay** [comment]
Actually, just had a think and a play with this, and I don't see an issue. The quote was: 

> React re-renders all nested components even if their props haven't changed.

This is in fact regardless of how the options here are passed. Providers like `RovingTabIndexProvider` always have `props.children` because by their nature they provide some functionality to some children. If the component that renders the `RovingTabIndexProvider` re-renders for some reason, then the children that the provider wraps will always be re-rendered, unless the children themselves use memoization (i.e., `React.memo()`). Even if no `options` object is passed or if the options are instead passed as primitive values, if the parent component re-renders then the children wrapped by the provider will re-render. (And it is only by that parent component re-rendering that the `options` prop will get a new value.)

This fact is why the article you link to includes mention of [this tweet](https://twitter.com/sophiebits/status/1228942768543686656) by Sophie Alpert.

**Comment by kripod** [comment]
Oh, I see, thank you for your research. I’m closing this for now.
